name: Print txt file
on:
  push:
    branches:
      -main
        
    pull_request:
    branches:
      -main

jobs:
  read_the_file:
    runs-on: ubuntu-Latest
    steps:
      -name: Git checkout koren
      uses: actions/checkout@v2
      -name: Read the txt file
      run: |
        ls -l
        cat Atik.txt